spring.application.name=innovatechBackend
server.port=8080

# URLs base (Sin /listar al final para que sean flexibles)
url.proyectos=http://localhost:8081/api/projects
url.recursos=http://localhost:8082/api/resources
url.analitica=http://localhost:8083/api/analytics